# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib_books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='library',
            field=models.ForeignKey(default='Technical', on_delete=django.db.models.deletion.CASCADE, to='lib_books.Library'),
        ),
    ]
