# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_books', '0003_book_library'),
        ('lib_books', '0002_auto_20160405_1711'),
    ]

    operations = [
    ]
