# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib_books', '0004_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='library',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='lib_books.Library'),
        ),
    ]
